import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFileSync, mkdirSync, unlinkSync } from 'fs';
import { join } from 'path';
import { createTempDir, cleanTempDir, runCLI } from './helpers.js';

describe('daedalion validate', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir();
    runCLI('init --with-example', tempDir);
    runCLI('build', tempDir);
  });

  afterEach(async () => {
    await cleanTempDir(tempDir);
  });

  it('passes on valid project', () => {
    const output = runCLI('validate', tempDir);
    expect(output).toContain('✓');
  });

  it('fails when spec has no requirements', () => {
    const specPath = join(tempDir, 'openspec/specs/broken/spec.md');
    mkdirSync(join(tempDir, 'openspec/specs/broken'), { recursive: true });
    writeFileSync(specPath, '# Broken Spec\n\nNo requirements here.');

    let error: any;
    try {
      runCLI('validate', tempDir);
    } catch (e) {
      error = e;
    }

    expect(error).toBeDefined();
    expect(error.stderr || error.stdout || error.message).toContain('has no requirements');
  });

  it('fails when requirement lacks scenarios', () => {
    const specPath = join(tempDir, 'openspec/specs/example/spec.md');
    writeFileSync(specPath, `# Example Spec

## Requirements

### Requirement: Missing Scenarios
The system SHALL do something.
`);

    let error: any;
    try {
      runCLI('validate', tempDir);
    } catch (e) {
      error = e;
    }

    expect(error).toBeDefined();
    expect(error.stderr || error.stdout || error.message).toContain('lacks scenarios');
  });

  it('fails when skill missing for spec', () => {
    const specPath = join(tempDir, 'openspec/specs/orphan/spec.md');
    mkdirSync(join(tempDir, 'openspec/specs/orphan'), { recursive: true });
    writeFileSync(specPath, `# Orphan Spec

## Requirements

### Requirement: Test
SHALL test.

#### Scenario: Test
- WHEN test
- THEN pass
`);

    let error: any;
    try {
      runCLI('validate', tempDir);
    } catch (e) {
      error = e;
    }

    expect(error).toBeDefined();
    expect(error.stderr || error.stdout || error.message).toContain('Missing skill');
  });

  it('orphan rule ignores skill dirs not listed in the manifest (hand-maintained)', () => {
    // beforeEach: init + build → manifest lists only 'example' skill
    // Add a hand-maintained skill dir not generated by daedalion
    mkdirSync(join(tempDir, '.github/skills/hand-maintained'), { recursive: true });
    writeFileSync(join(tempDir, '.github/skills/hand-maintained/SKILL.md'), '# Hand-maintained\n');

    const output = runCLI('validate', tempDir);
    expect(output).toContain('✓');
  });

  it('orphan rule passes for skill built from a delta spec (not yet promoted to canonical)', () => {
    // Add delta spec for a new domain to the existing change
    mkdirSync(join(tempDir, 'openspec/changes/example-feature/specs/delta-domain'), { recursive: true });
    writeFileSync(
      join(tempDir, 'openspec/changes/example-feature/specs/delta-domain/spec.md'),
      `# Delta Domain\n\n## Requirements\n\n### Requirement: Delta Req\n\nShall do delta.\n\n#### Scenario: S\n- WHEN x\n- THEN y\n`
    );
    // Rebuild: manifest now includes delta-domain skill
    runCLI('build', tempDir);

    // validate: delta-domain is in manifest AND discoverSpecs finds its delta spec → no orphan error
    const output = runCLI('validate', tempDir);
    expect(output).toContain('✓');
  });

  it('orphan rule skips entirely when no manifest exists', () => {
    // Delete the manifest written by beforeEach's build
    unlinkSync(join(tempDir, '.github/.daedalion-manifest.json'));

    // Add a skill dir that would be flagged as orphan if manifest existed
    mkdirSync(join(tempDir, '.github/skills/orphan-without-spec'), { recursive: true });
    writeFileSync(join(tempDir, '.github/skills/orphan-without-spec/SKILL.md'), '# Orphan\n');

    const output = runCLI('validate', tempDir);
    expect(output).toContain('✓');
  });
});
