import { ensureDir } from '../utils.js';
import { writeFileSync } from 'fs';
import { join } from 'path';
import type { GeneratedFile, BuildOptions, Spec } from '../types.js';

export function generateAgentsIndex(
  specs: Spec[],
  outputDir: string,
  options: BuildOptions = {},
): GeneratedFile {
  const agentsPath = join(outputDir, 'AGENTS.md');

  let content = `# Agents\n\n> Auto-generated by Daedalion. Edit the specs in \`openspec/\` and run \`daedalion build\`.\n\n`;

  if (specs.length === 0) {
    content += `No agents compiled yet.\n`;
  } else {
    content += `| Domain | Description | Agent file |\n`;
    content += `|--------|-------------|------------|\n`;
    for (const spec of specs) {
      const description = spec.requirements.length > 0
        ? spec.requirements[0].name
        : spec.title;
      const agentFile = `.github/agents/${spec.domain}.agent.md`;
      content += `| ${spec.domain} | ${description} | [${spec.domain}.agent.md](${agentFile}) |\n`;
    }
  }

  content += '\n';

  if (options.dryRun) {
    return { path: agentsPath, content };
  }

  ensureDir(agentsPath);
  writeFileSync(agentsPath, content);
  return { path: agentsPath, content };
}
