import { readFileSync, existsSync } from 'fs';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { ensureDir } from '../utils.js';

export function generateInstructions(openspecDir, outputDir, options = {}) {
  const projectPath = join(openspecDir, 'project.md');
  const instructionsPath = join(outputDir, 'copilot-instructions.md');

  // Check for root AGENTS.md (openspecDir is ./openspec, so parent is project root)
  const projectRoot = dirname(openspecDir);
  const agentsPath = join(projectRoot, 'AGENTS.md');
  const hasAgents = existsSync(agentsPath);

  let content;

  if (existsSync(projectPath)) {
    const projectContent = readFileSync(projectPath, 'utf-8');
    content = transformProjectToInstructions(projectContent, hasAgents);
  } else {
    content = generateDefaultInstructions(hasAgents);
  }

  if (options.dryRun) {
    return { path: instructionsPath, content };
  }

  ensureDir(instructionsPath);
  writeFileSync(instructionsPath, content);
  return { path: instructionsPath, content };
}

function transformProjectToInstructions(projectContent, hasAgents) {
  const agentsSection = hasAgents ? `
## OpenSpec Workflow

This project uses OpenSpec for specification-driven development.
See \`AGENTS.md\` for workflow instructions on creating and implementing changes.

` : '';

  const header = `# Copilot Instructions

> Auto-generated by Daedalion from openspec/project.md
> Do not edit directly - changes will be overwritten.
${agentsSection}`;

  return header + projectContent;
}

function generateDefaultInstructions(hasAgents) {
  const agentsSection = hasAgents ? `
## OpenSpec Workflow

This project uses OpenSpec for specification-driven development.
See \`AGENTS.md\` for workflow instructions on creating and implementing changes.

` : '';

  return `# Copilot Instructions

> Auto-generated by Daedalion
> Do not edit directly - changes will be overwritten.
${agentsSection}
## Project Overview

This project uses OpenSpec for specification-driven development.

## Working with Specifications

- Specs are in \`openspec/specs/\`
- Active changes are in \`openspec/changes/\`
- Use the available skills and agents for implementation guidance

## Available Resources

Check the \`.github/skills/\` directory for implementation guides.
Check the \`.github/agents/\` directory for specialized agents.
Check the \`.github/prompts/\` directory for slash commands.
`;
}
