import { readFileSync, existsSync } from 'fs';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ensureDir } from '../utils.js';

export function generateInstructions(openspecDir, outputDir, options = {}) {
  const projectPath = join(openspecDir, 'project.md');
  const instructionsPath = join(outputDir, 'copilot-instructions.md');

  let content;

  if (existsSync(projectPath)) {
    const projectContent = readFileSync(projectPath, 'utf-8');
    content = transformProjectToInstructions(projectContent);
  } else {
    content = generateDefaultInstructions();
  }

  if (options.dryRun) {
    return { path: instructionsPath, content };
  }

  ensureDir(instructionsPath);
  writeFileSync(instructionsPath, content);
  return { path: instructionsPath, content };
}

function transformProjectToInstructions(projectContent) {
  // Note: GitHub Copilot natively reads AGENTS.md files, so no reference needed here.
  // See: https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions
  const header = `# Copilot Instructions

> Auto-generated by Daedalion from openspec/project.md
> Do not edit directly - changes will be overwritten.

`;

  return header + projectContent;
}

function generateDefaultInstructions() {
  // Note: GitHub Copilot natively reads AGENTS.md files, so no reference needed here.
  // See: https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions
  return `# Copilot Instructions

> Auto-generated by Daedalion
> Do not edit directly - changes will be overwritten.

## Project Overview

This project uses OpenSpec for specification-driven development.

## Working with Specifications

- Specs are in \`openspec/specs/\`
- Active changes are in \`openspec/changes/\`
- Use the available skills and agents for implementation guidance

## Available Resources

Check the \`.github/skills/\` directory for implementation guides.
Check the \`.github/agents/\` directory for specialized agents.
Check the \`.github/prompts/\` directory for slash commands.
`;
}
