import { readFileSync, existsSync } from 'fs';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ensureDir } from '../utils.js';
import type { GeneratedFile, BuildOptions } from '../types.js';

export function generateInstructions(openspecDir: string, outputDir: string, options: BuildOptions = {}): GeneratedFile {
  const projectPath: string = join(openspecDir, 'project.md');
  const instructionsPath: string = join(outputDir, 'copilot-instructions.md');

  let content: string;

  if (existsSync(projectPath)) {
    const projectContent: string = readFileSync(projectPath, 'utf-8');
    content = transformProjectToInstructions(projectContent);
  } else {
    content = generateDefaultInstructions();
  }

  if (options.dryRun) {
    return { path: instructionsPath, content };
  }

  ensureDir(instructionsPath);
  writeFileSync(instructionsPath, content);
  return { path: instructionsPath, content };
}

function transformProjectToInstructions(projectContent: string): string {
  const header: string = `# Copilot Instructions

> Auto-generated by Daedalion from openspec/project.md
> Do not edit directly - changes will be overwritten.

`;

  return header + projectContent;
}

function generateDefaultInstructions(): string {
  return `# Copilot Instructions

> Auto-generated by Daedalion
> Do not edit directly - changes will be overwritten.

## Project Overview

This project uses OpenSpec for specification-driven development.

## Working with Specifications

- Specs are in \`openspec/specs/\`
- Active changes are in \`openspec/changes/\`
- Use the available skills and agents for implementation guidance

## Available Resources

Check the \`.github/skills/\` directory for implementation guides.
Check the \`.github/agents/\` directory for specialized agents.
Check the \`.github/prompts/\` directory for slash commands.
`;
}
