import { readFileSync, existsSync } from 'fs';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ensureDir } from '../utils.js';
import type { GeneratedFile, BuildOptions, Spec } from '../types.js';

export function generateInstructions(
  openspecDir: string,
  outputDir: string,
  options: BuildOptions = {},
  specs: Spec[] = []
): GeneratedFile {
  const projectPath: string = join(openspecDir, 'project.md');
  const instructionsPath: string = join(outputDir, 'copilot-instructions.md');

  const conventionsSection = extractConventionsSection(projectPath);
  const content = buildInstructionsContent(specs, conventionsSection);

  if (options.dryRun) {
    return { path: instructionsPath, content };
  }

  ensureDir(instructionsPath);
  writeFileSync(instructionsPath, content);
  return { path: instructionsPath, content };
}

function extractConventionsSection(projectPath: string): string | null {
  if (!existsSync(projectPath)) {
    return null;
  }

  const projectContent = readFileSync(projectPath, 'utf-8');
  const lines = projectContent.split('\n');

  let inConventions = false;
  const conventionLines: string[] = [];

  for (const line of lines) {
    if (/^##\s+(Project\s+)?Conventions\s*$/i.test(line)) {
      inConventions = true;
      continue;
    }
    if (inConventions) {
      // Stop at the next ## heading
      if (/^## /.test(line)) {
        break;
      }
      conventionLines.push(line);
    }
  }

  if (conventionLines.length === 0) {
    return null;
  }

  // Trim leading/trailing blank lines from the captured block
  const trimmed = conventionLines.join('\n').trim();
  return trimmed.length > 0 ? trimmed : null;
}

function buildInstructionsContent(specs: Spec[], conventions: string | null): string {
  const lines: string[] = [];

  lines.push('# Copilot Instructions');
  lines.push('');
  lines.push('> Auto-generated by Daedalion. Do not edit — rebuild with `daedalion build`.');

  if (specs.length > 0) {
    lines.push('');
    lines.push('## Project Domains');
    lines.push('');
    lines.push('This project has the following spec domains:');
    for (const spec of specs) {
      lines.push(`- **${spec.domain}** — use \`#${spec.domain}\` skill or \`.github/agents/${spec.domain}.agent.md\``);
    }
  }

  if (conventions !== null) {
    lines.push('');
    lines.push('## Conventions');
    lines.push('');
    lines.push(conventions);
  }

  lines.push('');
  lines.push('## Working with Specs');
  lines.push('');
  lines.push('Specifications are in `openspec/`. Use `.github/skills/` for implementation guidance and `.github/agents/` for domain agents.');
  lines.push('');

  return lines.join('\n');
}
